spring.application.name=backend


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url= jdbc:mysql://localhost:3306/nexaerp
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


server.port=8085





# JWT Configuration
app.jwt.secret = nexaerp-jwt-secret-key-2025-very-long-and-secure-string-minimum-256-bit
app.jwt.access-token-expiration = 900000
app.jwt.refresh-token-expiration = 604800000

# Security Configuration
app.security.max-failed-attempts = 5
app.security.lock-duration-minutes = 30